require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "**/*_spec.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
