env:
  global:
    - CC_TEST_REPORTER_ID=ced551cb55b574bb553181cb1c7abae8452a4f7f6e92df83633984a03693e284

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - ruby --version | grep '^ruby 2\.3\.' > /dev/null || gem install rubocop

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ruby --version | grep '^ruby 2\.3\.' > /dev/null || rubocop
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
